### ISSUE TITLE
"uploading: file" when downloading?

### ISSUE THREAD

**Issue by bit4man** [openshift/oc-mirror#48] opened 2021-08-24 15:44 UTC
During the first "oc-bundle create full" run, when a given version of OCP is downloaded, the text/prompt is "uploading": uploading: 

> file://openshift/release sha256:2e41ca5fb22b44b82ce7d08e7436d0965776843a45bcdcf5fc2a38fafe4f027b 9.534MiB
> uploading: file://openshift/release sha256:ae411670fc26c36fee9fd1232139e051b31ebbed7b411f22dc21fd153ff06456 85.64MiB
> uploading: file://openshift/release sha256:8795e1eff4a91cb42c085fd44ce7724e42b5f536da218a88bcbe5d23b3376eda 103.5MiB
> uploading: file://openshift/release sha256:917fc69dd02cce554468e1bce0969c5dc133ba8a0427d08626fd7a3cd461faa1 28.61MiB
> uploading: file://openshift/release sha256:fdae22ebfdbf3ab549eeabe88fcf4d14df92758a6d0080989af85810afdbff00 515.6KiB

I would expect downloading and not uploading in this context?

**Comment by afflom** [comment] 2021-08-24 15:51
Thank you for your interest in bundle! This is expected behavior due to the way that we are calling oc mirror. We will need to PR oc to export the needed functions and build a custom Run() within bundle, that way we can control the output. I believe that the output  you are seeing here is similar to how skopeo handles saving images from a registry to a file.

**Comment by afflom** [comment] 2021-09-16 20:32
This will be fixed from #82

**Closed** 2022-02-13 22:58 UTC
Labels: kind/feature, lifecycle/rotten
