### ISSUE TITLE
INVALID_REQUEST: Unable to decode repository and actions: registry:catalog:*; map[]

### ISSUE THREAD

**Issue by bit4man** [openshift/oc-mirror#204] opened 2021-11-30 17:00 UTC
Trying to run a simple example mirroring to a local network quay repository:

```console
$ oc-mirror --config example-config.yaml docker://quay2.example.org/ocprepo/mirror
INFO Verifying pull secrets                       
INFO Creating directory: oc-mirror-workspace/src/publish 
INFO Creating directory: oc-mirror-workspace/src/v2 
INFO Creating directory: oc-mirror-workspace/src/charts 
error: GET https://quay2.example.org/v2/auth?scope=registry%3Acatalog%3A%2A&service=quay2.example.org: INVALID_REQUEST: Unable to decode repository and actions: registry:catalog:*; map[]
```
Before running this command, logged into quay2 with the ocprepo user using "podman login". 

# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?

Run fails with a repository error (see above)
Attach the relevant portions of your `.openshift_bundle.log`.
No file generated.

# What you expected to happen?

OCP 4.9 pull/mirror completes.

# How to reproduce it (as minimally and precisely as possible)?
Ran with the following configuration.
[example-config.yaml.txt](https://github.com/openshift/oc-mirror/files/7627409/example-config.yaml.txt)

```console
$ oc-mirror --config example-config.yaml docker://quay2.example.org/ocprepo/mirror
```

# Anything else we need to know?

Enter text here.

# References

Enter text here.

**Comment by jpower432** [comment] 2021-11-30 17:09
@bit4man Thanks for your feedback! We have another open issue to address this error with quay #168.

**Comment by jpower432** [comment] 2021-11-30 17:15
Duplicate of #168

**Comment by afflom** [comment] 2022-01-17 22:26
@bit4man can you verify that this has been resolved in main?

**Closed** 2022-06-17 00:46 UTC
Labels: lifecycle/rotten
